# Platform Backend - QuixAlert!

###
# group: Firebase User
# @name All
GET {{base_url}}/users-firebase/

###
# group: Firebase User
# @name By id
GET {{base_url}}/users-firebase/lnnvN64SjlOdsecRs008fa1AtYr2
