# Platform Backend - QuixAlert!

###
# group: Reports
# @name All
GET {{base_url}}/report

###
# group: Reports
# @name By report id
GET {{base_url}}/report/-NgaamcbkEIyh9VJfhwd

###
# group: Animals
# @name By user id
GET {{base_url}}/report/user/wAw9lsuk0Catoq67ylykmOM8pqx2

